#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=50

parse_device() {
	local cfg="$1" ip download upload
	
	config_get ip "$cfg" ip
	config_get download "$cfg" download
	config_get upload "$cfg" upload
	
	eqos add $ip $download $upload
	
	# If IPv6 is enabled, also add IPv6 rules based on MAC address
	config_get_bool ipv6_enabled eqos ipv6_enabled 0
	if [ $ipv6_enabled -eq 1 ]; then
		# Get MAC address for the IP
		mac=$(ip neigh show $ip | awk '{print $5}' | head -n1)
		if [ -n "$mac" ]; then
			eqos add_ipv6 $mac $download $upload
		fi
	fi
}

eqos_start() {
	local cfg="$1" enabled download upload
	
	config_get_bool enabled "$cfg" enabled 0
	[ $enabled -eq 0 ] && return 0
	
	config_get download "$cfg" download
	config_get upload "$cfg" upload
	
	eqos start $download $upload
	
	config_foreach parse_device device
}

start() {
	eqos stop
	
	config_load eqos
	config_foreach eqos_start eqos
}

stop() {
	eqos stop
}