name: Build-OpenWrt-diskman-APK

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '发布版本号 (留空不发布)'
        required: false
        default: ''
      text:
        description: '发布说明'
        required: false
        default: ''
env:
  TAG: "${{ github.event.inputs.tag }}"
  TZ: Asia/Shanghai
permissions:
  contents: write
jobs:
  build:
    name: Build APK-${{ matrix.arch }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64_cortex-a53]

    steps:
      - uses: actions/checkout@v4
        with:
          path: 'package/packages_ci'  # 关键路径修正

      - name: Setup OpenWrt feeds
        run: |
          # 初始化自定义 feed
          echo 'src-link packages_ci $GITHUB_WORKSPACE/package/packages_ci' >> feeds.conf
          
          # 更新所有 feeds
          ./scripts/feeds update -a
          
          # 安装依赖
          ./scripts/feeds install -a

      - name: Building APK packages
        uses: sbwml/openwrt-gh-action-sdk@v2.0.0
        env:
          TARGET: qualcommax/ipq807x  # 明确指定目标平台
          SDK: SNAPSHOT
          FEEDS_CONF: feeds.conf       # 显式指定配置文件
          PACKAGES: luci-app-diskman   # 仅编译主应用
          VERBOSE: 1                   # 显示详细日志

      - name: Find and upload artifacts
        run: |
          # 查找生成的 APK 文件
          find bin/ -name '*.apk' -exec echo "Found APK: {}" \;
          
          # 创建压缩包 (保留目录结构)
          find bin/ -name '*.apk' -print0 | xargs -0 zip -9r diskman-${{ matrix.arch }}-apk.zip

      - name: Release Assets
        if: ${{ github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          body: |
            ### APK 安装指南
            ```bash
            apk add --allow-untrusted luci-app-diskman.apk
            ```
            ${{ github.event.inputs.text }}
          files: |
            diskman-*-apk.zip
